name: Build and Push Docker Image

on:
  push:
    branches:
      - main

# Required permissions to write packages to your GitHub profile
permissions:
  packages: write
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This saves it as ghcr.io/urgew/docker-project/github-docker-test1:latest
          tags: ghcr.io/${{ github.repository }}/github-docker-test1:latest
